/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyewaanlapanganfutsal;

import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.swing.UIManager;

/**
 *
 * @author ASUS
 */
public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Penyewaan
     */
    public Pemesanan() {
        initComponents();
        tabel();
        isicmbkodelapangan();
        isicmbtanggalpesan();
        isicmbjampesan();
        isicmbpemesan();
    }
    
    void isicmbkodelapangan(){
        for (int i = 1; i <= 10; i++) {
            cmbkodelapangan.addItem("Lapangan " + Integer.toString(i));
        }
    }
    
    void isicmbtanggalpesan(){
        for (int i = 1; i <= 31; i++) {
            cmbtgl.addItem(Integer.toString(i));
        }
        
        for (int i = 1; i <= 12; i++) {
            cmbbln.addItem(Integer.toString(i));
        }
        
        for (int i = 2021; i <= 2025; i++) {
            cmbthn.addItem(Integer.toString(i));
        }
    }
    
    void isicmbjampesan(){
        for (int i = 8; i <= 22; i++) {
            cmbjam1.addItem(Integer.toString(i) + ":00");
        }
        
        for (int i = 8; i <= 22; i++) {
            cmbjam2.addItem(Integer.toString(i) + ":00");
        }
        
    }
    
    void isicmbpemesan(){
        ResultSet isitabel = new Login().selectquery("Select * from member");
        try {
            while (isitabel.next()) {
                cmbpemesanan.addItem(isitabel.getString("id_member") + " / " + 
                                     isitabel.getString("nama_pemesan") + " / " +
                                     isitabel.getString("nama_team"));
            }
        } catch (SQLException ex) {
            System.err.println("Gagal Load Data " + ex.getMessage());
        }
    }
    
    void kosong(){
        cmbkodelapangan.setSelectedItem("---Pilih Lapangan---");
        cmbtgl.setSelectedItem("---Pilih Tanggal---");
        cmbbln.setSelectedItem("---Pilih Bulan---");
        cmbthn.setSelectedItem("---Pilih Tahun---");
        cmbjam1.setSelectedItem("---Pilih Jam Mulai---");
        cmbjam2.setSelectedItem("---Pilih Jam Selesai---");
        cmbpemesanan.setSelectedItem("---Pilih Member---");
    }
    
    void tabel () {
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("ID Pemesanan");
        tbl.addColumn("Kode Lapangan");
        tbl.addColumn("Tanggal Pemesanan");
        tbl.addColumn("Waktu");
        tbl.addColumn("Durasi");
        tbl.addColumn("ID Member");
        tbl.addColumn("Status Bayar");
        tblpemesan.setModel(tbl);
        
        ResultSet isitabel = new Login().selectquery("Select * from pemesanan");
        try {
            while (isitabel.next()) {
                tbl.addRow(new Object[]{
                    isitabel.getString("id_pemesanan"),
                    isitabel.getString("kode_lapangan"),
                    isitabel.getString("tanggal_pemesanan"),
                    isitabel.getString("waktu"),
                    isitabel.getString("durasi"),
                    isitabel.getString("id_member"),
                    isitabel.getString("status_bayar")
                });
            }
        } catch (SQLException ex) {
            System.err.println("Gagal Load Data " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbkodelapangan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbtgl = new javax.swing.JComboBox<>();
        cmbbln = new javax.swing.JComboBox<>();
        cmbthn = new javax.swing.JComboBox<>();
        cmbjam1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbjam2 = new javax.swing.JComboBox<>();
        btnpesan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpemesan = new javax.swing.JTable();
        cmbpemesanan = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pemesanan Lapangan Futsal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Kode Lapangan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Tanggal Pemesanan");

        cmbkodelapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Lapangan---" }));
        cmbkodelapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodelapanganActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Waktu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Pemesan");

        cmbtgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Tanggal---" }));

        cmbbln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Bulan---" }));

        cmbthn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Tahun---" }));

        cmbjam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Jam Mulai---" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sampai");

        cmbjam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Jam Selesai---" }));

        btnpesan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbatal.setText("Kembali");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        tblpemesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblpemesan);

        cmbpemesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Member---" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbkodelapangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnbatal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbthn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbjam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbjam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cmbpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbkodelapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbthn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbjam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbjam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cmbpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesan)
                    .addComponent(btnbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbkodelapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodelapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkodelapanganActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String getjammulai = cmbjam1.getSelectedItem().toString();
        String getjamselesai = cmbjam2.getSelectedItem().toString();
        
        DateFormat Format = new SimpleDateFormat("HH:mm");
        
        Date jammulai = null;
        Date jamselesai = null;
        
        try{
            jammulai = Format.parse(getjammulai);
            jamselesai = Format.parse(getjamselesai);   
        }catch ( ParseException e ){
            e.printStackTrace();
    	}
        
        int durasi = (int) (jamselesai.getTime() - jammulai.getTime()) / (60 * 60 * 1000) % 24;
        
        String strjammulai = Format.format(jammulai);
        String strjamselesai = Format.format(jamselesai);
        
        String insertTableSQL = "INSERT INTO `pemesanan` "
                              + "(`id_pemesanan`, `kode_lapangan`, `tanggal_pemesanan`, `waktu`, "
                              + "`durasi`, `id_member`, `status_bayar`) VALUES "
                              + "(NULL, " 
                              + "'" + cmbkodelapangan.getSelectedItem() 
                              + "', '" + cmbthn.getSelectedItem() + "-" + cmbbln.getSelectedItem() + "-" + cmbtgl.getSelectedItem() 
                              + "', '" + strjammulai + "-" + strjamselesai 
                              + "', '" + durasi 
                              + "', '" + cmbpemesanan.getSelectedItem() 
                              + "', 'Belum Bayar')"; 
        new Login().query(insertTableSQL);
        kosong();
        tabel();
    }//GEN-LAST:event_btnpesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnpesan;
    private javax.swing.JComboBox<String> cmbbln;
    private javax.swing.JComboBox<String> cmbjam1;
    private javax.swing.JComboBox<String> cmbjam2;
    private javax.swing.JComboBox<String> cmbkodelapangan;
    private javax.swing.JComboBox<String> cmbpemesanan;
    private javax.swing.JComboBox<String> cmbtgl;
    private javax.swing.JComboBox<String> cmbthn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblpemesan;
    // End of variables declaration//GEN-END:variables
}
